INSERT INTO denominations (name, description, status) VALUES
('Catholicism-Roman Catholic', 'The Roman Catholic Church is the largest Christian church, led by the Pope, with a rich tradition of sacraments, liturgy, and global presence.', 'active'),
('Catholicism-Eastern Catholic', 'Eastern Catholic Churches are in full communion with the Pope but retain their own liturgical rites, traditions, and governance.', 'active'),
('Orthodoxy-Eastern Orthodox', 'The Eastern Orthodox Church emphasizes tradition, liturgy, and the seven ecumenical councils; it is organized into autocephalous regional churches.', 'active'),
('Orthodoxy-Oriental Orthodox', 'Oriental Orthodox Churches reject the Council of Chalcedon and maintain ancient Christian traditions, mainly in Egypt, Ethiopia, and Armenia.', 'active'),
('Protestantism-Anglican', 'The Anglican Church emerged from the English Reformation, blending Catholic liturgy with Protestant theology and episcopal governance.', 'active'),
('Protestantism-Lutheran', 'Lutheran churches follow the teachings of Martin Luther, emphasizing salvation by faith alone and the authority of Scripture.', 'active'),
('Protestantism-Presbyterian', 'Presbyterianism is a Reformed tradition governed by elders, emphasizing the sovereignty of God and covenant theology.', 'active'),
('Protestantism-Methodist', 'Methodism arose from the teachings of John Wesley, focusing on personal holiness, social justice, and structured spiritual practices.', 'active'),
('Protestantism-Baptist', 'Baptist churches emphasize believer''s baptism, congregational governance, and religious freedom.', 'active'),
('Protestantism-Reformed', 'Reformed churches follow Calvinist theology, stressing God''s sovereignty, predestination, and covenantal living.', 'active'),
('Protestantism-Pentecostal', 'Pentecostalism emphasizes the gifts of the Holy Spirit, including speaking in tongues, prophecy, and healing.', 'active'),
('Protestantism-Non-denominational', 'Non-denominational churches operate independently of historic denominations, often focusing on personal faith and Bible teaching.', 'active'),
('Protestantism-Charismatic', 'Charismatic Christians emphasize modern expressions of the Holy Spirit''s gifts, similar to Pentecostalism, within traditional churches.', 'active'),
('Protestantism-Not Listed', 'A Protestant church or community not categorized under the main listed Protestant denominations.', 'active'),
('Evangelical-Pentecostal', 'Evangelical Pentecostals emphasize personal conversion, the authority of Scripture, and the active presence of the Holy Spirit.', 'active'),
('Evangelical-Non-denominational', 'Evangelical non-denominational churches focus on personal faith, Bible teaching, and spreading the gospel outside traditional denominations.', 'active'),
('Evangelical-Charismatic', 'Evangelical Charismatics blend evangelical theology with modern expressions of the Holy Spirit''s gifts.', 'active'),
('Evangelical-Not Listed', 'An evangelical church not categorized under the main listed evangelical denominations.', 'active'),
('Adventist-Seventh-day Adventist', 'The Seventh-day Adventist Church observes Saturday as the Sabbath, emphasizes Christ''s second coming, and promotes holistic health.', 'active'),
('Adventist-Mormon', 'Mormons, or members of The Church of Jesus Christ of Latter-day Saints, follow modern revelations and unique scriptures alongside the Bible.', 'active'),
('Adventist-Jehovah''s Witnesses', 'Jehovah''s Witnesses emphasize Bible study, evangelism, and the name of God as Jehovah, rejecting certain mainstream Christian doctrines.', 'active'),
('Adventist-Not Listed', 'An Adventist-related church or community not categorized under the main listed Adventist denominations.', 'active'),
('Anabaptist-Mennonite', 'Mennonites emphasize pacifism, community living, adult baptism, and discipleship following the teachings of Menno Simons.', 'active'),
('Anabaptist-Amish', 'Amish communities live simple, traditional lives, emphasizing separation from modern society and strict adherence to Anabaptist principles.', 'active'),
('Anabaptist-Hutterites', 'Hutterites live in communal colonies, sharing property and resources, practicing Anabaptist traditions of adult baptism and pacifism.', 'active'),
('Anabaptist-Not Listed', 'An Anabaptist church or community not categorized under the main listed Anabaptist denominations.', 'active'),
('Other-Quakers', 'Quakers, or the Religious Society of Friends, emphasize simplicity, peace, integrity, and direct experience of God in daily life.', 'active'),
('Other-Salvation Army', 'The Salvation Army is a Christian organization focused on social welfare, evangelism, and practical service to the needy.', 'active'),
('Other-Christian Science', 'Christian Science emphasizes spiritual healing through prayer and the teachings of Mary Baker Eddy, interpreting the Bible spiritually.', 'active'),
('Other-Unitarian', 'Unitarianism focuses on the oneness of God, rejects the Trinity, and encourages reason, freedom of belief, and individual conscience.', 'active'),
('Other-Not Listed', 'A Christian denomination or community not categorized under the main listed denominations.', 'active');
