INSERT INTO departments (name, description, category, created_at, organization_id) VALUES
('Human Resources Department', 'Responsible for recruitment, welfare, and staff management', 'church', NOW(), 29),
('Operations Department', 'Oversees general business operations', 'corporate', NOW(), 29),
('Community Outreach Department', 'Organizes outreach programs and engages with local communities', 'church', NOW(), 29),
('Worship Department', 'Coordinates services, worship sessions, and spiritual events', 'church', NOW(), 29),
('Church Administration Department', 'Manages day-to-day church operations, staff, and logistics', 'church', NOW(), 29),
('Volunteer Department', 'Coordinates and organizes volunteers for church and community events', 'church', NOW(), 29),
('Mission Department', 'Leads outreach programs, mission trips, and international aid efforts', 'church', NOW(), 29),
('Youth Ministry Department', 'Focuses on spiritual education and outreach for young people', 'church', NOW(), 29),
('Children''s Ministry Department', 'Provides educational programs and activities for children', 'church', NOW(), 29),
('Adult Ministry Department', 'Organizes adult bible study groups, spiritual growth, and fellowship', 'church', NOW(), 29),
('Prayer Ministry Department', 'Supports and leads prayer meetings and prayer chains', 'church', NOW(), 29),
('Music Ministry Department', 'Oversees music programs, including choirs and worship bands', 'church', NOW(), 29),
('Legal Department', 'Provides legal counsel and manages legal risks', 'corporate', NOW(), 29),
('Bible Study Department', 'Organizes and facilitates bible study groups and educational sessions', 'church', NOW(), 29),
('Church Finance Department', 'Handles the church''s financial affairs, including budgeting and tithing', 'church', NOW(), 29),
('Pastoral Care Department', 'Provides counseling, care, and support to church members', 'church', NOW(), 29),
('Event Planning Department', 'Organizes church events, conferences, and special services', 'church', NOW(), 29),
('Church Communications Department', 'Manages internal and external communications, including newsletters', 'church', NOW(), 29),
('Newcomer Integration Department', 'Helps integrate new members into the church community', 'church', NOW(), 29),
('Counseling Department', 'Offers spiritual and emotional counseling to church members', 'church', NOW(), 29),
('Senior Ministry Department', 'Provides spiritual support and programs for elderly members', 'church', NOW(), 29),
('Marriage and Family Ministry Department', 'Supports families and couples through counseling and educational resources', 'church', NOW(), 29),
('Church Media Department', 'Manages church media presence, including video and live-streaming', 'church', NOW(), 29),
('Outreach and Evangelism Department', 'Focuses on spreading the gospel and community outreach programs', 'church', NOW(), 29),
('Social Justice Department', 'Focuses on advocacy, equality, and social justice initiatives', 'church', NOW(), 29),
('International Missions Department', 'Coordinates global mission efforts, helping communities abroad', 'church', NOW(), 29),
('Church Facilities Department', 'Manages church building maintenance, safety, and resources', 'church', NOW(), 29),
('Marketing Department', 'Handles advertising, branding, and public relations', 'corporate', NOW(), 29),
('Sales Department', 'Manages sales strategies, client acquisition, and customer relationships', 'corporate', NOW(), 29),
('Customer Support Department', 'Supports customers through queries, issues, and service requests', 'corporate', NOW(), 29),
('Research and Development Department', 'Focuses on product innovation and technological advancements', 'corporate', NOW(), 29),
('Product Management Department', 'Oversees product life cycles, from ideation to delivery', 'corporate', NOW(), 29),
('Logistics Department', 'Manages the transportation and delivery of goods', 'corporate', NOW(), 29),
('Purchasing Department', 'Handles procurement of materials, services, and products', 'corporate', NOW(), 29),
('Security Department', 'Ensures safety and security of premises and personnel', 'corporate', NOW(), 29),
('IT Support Department', 'Provides technical support and troubleshooting for IT issues', 'corporate', NOW(), 29),
('Compliance Department', 'Ensures adherence to laws, regulations, and company policies', 'corporate', NOW(), 29),
('Public Relations Department', 'Manages company communications and media relations', 'corporate', NOW(), 29),
('Quality Assurance Department', 'Monitors and ensures product and service quality standards', 'corporate', NOW(), 29),
('Training and Development Department', 'Provides employee development, skill-building, and training programs', 'corporate', NOW(), 29),
('Sustainability Department', 'Focuses on environmental impact, sustainability initiatives, and green practices', 'corporate', NOW(), 29),
('Facilities Department', 'Manages company buildings, maintenance, and office resources', 'corporate', NOW(), 29),
('Strategy Department', 'Develops and implements long-term business strategies', 'corporate', NOW(), 29),
('Engineering Department', 'Designs and develops technical solutions, products, and systems', 'corporate', NOW(), 29),
('Content Creation Department', 'Creates written, visual, and multimedia content for marketing and communication', 'corporate', NOW(), 29),
('Business Development Department', 'Identifies and pursues new business opportunities and partnerships', 'corporate', NOW(), 29),
('Information Security Department', 'Protects data, networks, and systems from unauthorized access', 'corporate', NOW(), 29),
('Social Media Department', 'Manages the company’s social media presence and engagement', 'corporate', NOW(), 29),
('Inventory Department', 'Handles stock management, storage, and ordering of materials', 'corporate', NOW(), 29),
('Health and Safety Department', 'Ensures workplace health, safety, and regulatory compliance', 'corporate', NOW(), 29),
('Legal Affairs Department', 'Oversees all legal proceedings, corporate contracts, and disputes', 'corporate', NOW(), 29);
