import express from "express";
import {
  exportPayrollPDF,
  exportPayrollExcel
} from "./payrollReportsController.js";
import { exportProgramsCSV, exportProgramsPDF } from "./programReportsController.js";
import { exportAttendeesCSV, exportAttendeesPDF } from "./attendeesReportController.js";
import HqOrganization from "./hqOrganizationsReportController.js";
import Member from "./membersReportsController.js";
import Department from "./departmentReportsController.js";
import FollowUpsModel from "./followUpReportsController.js";
import FollowUpSessionsModel from "./followUpSessionReportsController.js";
import Income from "./incomeReportsController.js";
import Expense from "./expenseReportsController.js";
import Budget from "./budgetReportsController.js";
import ConvertsModel from "./convertsReportsController.js";
import Attendance from "./attandanceRerportsController.js";
import Congregant from "./congregantReportsController.js";
import Session from "./sessionsReportsController.js";
import Service from "./servicesReportsController.js";
import Visitor from "./visitorsReportsController.js";
import { verifyJWT } from "../../middleware/auth.js";

const router = express.Router();

router.get("/payroll/pdf", verifyJWT, exportPayrollPDF);
router.get("/payroll/excel", verifyJWT, exportPayrollExcel);
router.get("/programs/pdf", verifyJWT, exportProgramsPDF);
router.get("/programs/csv", verifyJWT, exportProgramsCSV);
router.get("/attendees/report/pdf", verifyJWT, exportAttendeesPDF);
router.get("/attendees/report/csv", verifyJWT, exportAttendeesCSV);
router.get("/hq_org/pdf", HqOrganization.exportHqOrgPDF);
router.get("/hq_org/excel", HqOrganization.exportHqOrgExcel);
router.get("/members/pdf", verifyJWT, Member.exportPDF);
router.get("/members/excel", verifyJWT, Member.exportExcel);
router.get("/members/csv", verifyJWT, Member.exportCSV);
router.get("/departments/pdf", verifyJWT, Department.exportPDF);
router.get("/departments/excel", verifyJWT, Department.exportExcel);
router.get("/departments/csv", verifyJWT, Department.exportCSV);
router.get("/followups/pdf", verifyJWT, FollowUpsModel.exportPDF);
router.get("/followups/excel", verifyJWT, FollowUpsModel.exportExcel);
router.get("/followups/csv", verifyJWT, FollowUpsModel.exportCSV);
router.get("/followups-sessions/pdf", verifyJWT, FollowUpSessionsModel.exportPDF);
router.get("/followups-sessions/excel", verifyJWT, FollowUpSessionsModel.exportExcel);
router.get("/followups-sessions/csv", verifyJWT, FollowUpSessionsModel.exportCSV);
router.get("/incomes/pdf", verifyJWT, Income.exportPDF);
router.get("/incomes/excel", verifyJWT, Income.exportExcel);
router.get("/incomes/csv", verifyJWT, Income.exportCSV);
router.get("/expenses/pdf", verifyJWT, Expense.exportPDF);
router.get("/expenses/excel", verifyJWT, Expense.exportExcel);
router.get("/expenses/csv", verifyJWT, Expense.exportCSV);
router.get("/budgets/pdf", verifyJWT, Budget.exportPDF);
router.get("/budgets/excel", verifyJWT, Budget.exportExcel);
router.get("/budgets/csv", verifyJWT, Budget.exportCSV);
router.get("/converts/pdf", verifyJWT, ConvertsModel.exportPDF);
router.get("/converts/excel", verifyJWT, ConvertsModel.exportExcel);
router.get("/converts/csv", verifyJWT, ConvertsModel.exportCSV);
router.get("/attendance/pdf", verifyJWT, Attendance.exportPDF);
router.get("/attendance/excel", verifyJWT, Attendance.exportExcel);
router.get("/attendance/csv", verifyJWT, Attendance.exportCSV);
router.get("/congregants/pdf", verifyJWT, Congregant.exportPDF);
router.get("/congregants/excel", verifyJWT, Congregant.exportExcel);
router.get("/congregants/csv", verifyJWT, Congregant.exportCSV);
router.get("/sessions/pdf", verifyJWT, Session.exportPDF);
router.get("/sessions/excel", verifyJWT, Session.exportExcel);
router.get("/sessions/csv", verifyJWT, Session.exportCSV);
router.get("/services/pdf", verifyJWT, Service.exportPDF);
router.get("/services/excel", verifyJWT, Service.exportExcel);
router.get("/services/csv", verifyJWT, Service.exportCSV);
router.get("/visitors/pdf", verifyJWT, Visitor.exportPDF);
router.get("/visitors/excel", verifyJWT, Visitor.exportExcel);
router.get("/visitors/csv", verifyJWT, Visitor.exportCSV);

export default router;
