import express from "express";
import {
  exportPayrollPDF,
  exportPayrollExcel
} from "./payrollReportsController.js";
import { exportProgramsCSV, exportProgramsPDF } from "./programReportsController.js";
import { exportAttendeesCSV, exportAttendeesPDF } from "./attendeesReportController.js";
import HqOrganization from "./hqOrganizationsReportController.js";
import Member from "./membersReportsController.js";
import Department from "./departmentReportsController.js";
import FollowUpsModel from "./followUpReportsController.js";
import FollowUpSessionsModel from "./followUpSessionReportsController.js";
import Income from "./incomeReportsController.js";
import Expense from "./expenseReportsController.js";
import Budget from "./budgetReportsController.js";
import ConvertsModel from "./convertsReportsController.js";
import Attendance from "./attandanceRerportsController.js";
import Congregant from "./congregantReportsController.js";
import Session from "./sessionsReportsController.js";
import Service from "./servicesReportsController.js";
import Visitor from "./visitorsReportsController.js";
import { verifyJWT } from "../../middleware/auth.js";

const router = express.Router();

router.get("/payroll/pdf", exportPayrollPDF);
router.get("/payroll/excel", exportPayrollExcel);
router.get("/programs/pdf", exportProgramsPDF);
router.get("/programs/csv", exportProgramsCSV);
router.get("/attendees/report/pdf", exportAttendeesPDF);
router.get("/attendees/report/csv", exportAttendeesCSV);
router.get("/hq_org/pdf", HqOrganization.exportHqOrgPDF);
router.get("/hq_org/excel", HqOrganization.exportHqOrgExcel);
router.get("/members/pdf", verifyJWT, Member.exportPDF);
router.get("/members/excel", verifyJWT, Member.exportExcel);
router.get("/members/csv", verifyJWT, Member.exportCSV);
router.get("/departments/pdf", Department.exportPDF);
router.get("/departments/excel", Department.exportExcel);
router.get("/departments/csv", Department.exportCSV);
router.get("/followups/pdf", FollowUpsModel.exportPDF);
router.get("/followups/excel", FollowUpsModel.exportExcel);
router.get("/followups/csv", FollowUpsModel.exportCSV);
router.get("/followups-sessions/pdf", FollowUpSessionsModel.exportPDF);
router.get("/followups-sessions/excel", FollowUpSessionsModel.exportExcel);
router.get("/followups-sessions/csv", FollowUpSessionsModel.exportCSV);
router.get("/incomes/pdf", Income.exportPDF);
router.get("/incomes/excel", Income.exportExcel);
router.get("/incomes/csv", Income.exportCSV);
router.get("/expenses/pdf", Expense.exportPDF);
router.get("/expenses/excel", Expense.exportExcel);
router.get("/expenses/csv", Expense.exportCSV);
router.get("/budgets/pdf", Budget.exportPDF);
router.get("/budgets/excel", Budget.exportExcel);
router.get("/budgets/csv", Budget.exportCSV);
router.get("/converts/pdf", ConvertsModel.exportPDF);
router.get("/converts/excel", ConvertsModel.exportExcel);
router.get("/converts/csv", ConvertsModel.exportCSV);
router.get("/attendance/pdf", Attendance.exportPDF);
router.get("/attendance/excel", Attendance.exportExcel);
router.get("/attendance/csv", Attendance.exportCSV);
router.get("/congregants/pdf", Congregant.exportPDF);
router.get("/congregants/excel", Congregant.exportExcel);
router.get("/congregants/csv", Congregant.exportCSV);
router.get("/sessions/pdf", Session.exportPDF);
router.get("/sessions/excel", Session.exportExcel);
router.get("/sessions/csv", Session.exportCSV);
router.get("/services/pdf", Service.exportPDF);
router.get("/services/excel", Service.exportExcel);
router.get("/services/csv", Service.exportCSV);
router.get("/visitors/pdf", verifyJWT, Visitor.exportPDF);
router.get("/visitors/excel", verifyJWT, Visitor.exportExcel);
router.get("/visitors/csv", verifyJWT, Visitor.exportCSV);

export default router;
