--SELECT * FROM permissions
INSERT INTO permissions ("name", "path", "method", "description") VALUES
('Create Organization', '/organizations/register', 'POST', 'Create a new organization'),
('View Organizations', '/organizations', 'GET', 'View all organizations'),
('Edit Organization', '/organizations/{orgId}', 'PUT', 'Edit organization details'),
('Delete Organization', '/organizations/{orgId}', 'DELETE', 'Delete an organization'),
('Create User', '/users/register', 'POST', 'Create a new user'),
('View Users', '/users', 'GET', 'View all users'),
('Edit User', '/users/{userId}', 'PUT', 'Edit user details'),
('Delete User', '/users/{userId}', 'DELETE', 'Delete a user'),
('View Dashboard', '/dashboard', 'GET', 'View the main dashboard'),
('View Pastoral Dashboard', '/pastoral/dashboard', 'GET', 'View the pastoral dashboard'),
('View Programs Dashboard', '/programs/dashboard', 'GET', 'View the programs dashboard'),
('View Ministry Dashboard', '/ministry/dashboard', 'GET', 'View the ministry dashboard'),
('View HR Dashboard', '/hr/dashboard', 'GET', 'View the HR dashboard'),
('View Governance Dashboard', '/governance/dashboard', 'GET', 'View the governance dashboard'),
('View Finance Dashboard', '/finance/dashboard', 'GET', 'View the finance dashboard'),
('View Donor Dashboard', '/donor/dashboard', 'GET', 'View the donor dashboard'),
('View Congregation Dashboard', '/congregation/dashboard', 'GET', 'View the congregation dashboard'),
('View Class Dashboard', '/class/dashboard', 'GET', 'View the class dashboard'),
('View Asset Dashboard', '/assets/dashboard', 'GET', 'View the asset management dashboard'),
('Add Asset', '/assets/addAsset', 'POST', 'Add a new asset'),
('View Assets', '/assets/assets', 'GET', 'View all assets'),
('Edit Asset', '/assets/{assetId}', 'PUT', 'Edit asset details'),
('Delete Asset', '/assets/{assetId}', 'DELETE', 'Delete an asset'),
('Add Donor', '/donor/addDonor', 'POST', 'Add a new donor'),
('View Donors', '/donor/donors', 'GET', 'View all donors'),
('Edit Donor', '/donor/{donorId}', 'PUT', 'Edit donor details'),
('Delete Donor', '/donor/{donorId}', 'DELETE', 'Delete a donor'),
('Add Donation', '/donor/addDonation', 'POST', 'Add a new donation'),
('View Donations', '/donor/donations', 'GET', 'View all donations'),
('Edit Donation', '/donor/{donationId}', 'PUT', 'Edit donation details'),
('Delete Donation', '/donor/{donationId}', 'DELETE', 'Delete a donation'),
('Add Member', '/congregation/addMember', 'POST', 'Add a new congregation member'),
('View Members', '/congregation/members', 'GET', 'View all congregation members'),
('Edit Member', '/congregation/{memberId}', 'PUT', 'Edit member details'),
('Delete Member', '/congregation/{memberId}', 'DELETE', 'Delete a congregation member'),
('Add Visitor', '/congregation/addVisitors', 'POST', 'Add a new visitor'),
('View Visitors', '/congregation/visitors', 'GET', 'View all visitors'),
('Edit Visitor', '/congregation/{visitorId}', 'PUT', 'Edit visitor details'),
('Delete Visitor', '/congregation/{visitorId}', 'DELETE', 'Delete a visitor'),
('View Congregation Attendance', '/congregation/attendance', 'GET', 'View congregation attendance records'),
('Record Attendance', '/congregation/recordAttendance', 'POST', 'Record congregation attendance'),
('Add Convert', '/congregation/addConvert', 'POST', 'Add a new convert record'),
('View Converts', '/congregation/converts', 'GET', 'View all converts'),
('Edit Convert', '/congregation/{convertId}', 'PUT', 'Edit convert details'),
('Delete Convert', '/congregation/{convertId}', 'DELETE', 'Delete a convert record'),
('View Asset Depreciation', '/assets/depreciation', 'GET', 'View asset depreciation details'),
('View Categories', '/assets/categories', 'GET', 'View asset categories'),
('Manage Asset Maintenance', '/assets/maintenance', 'GET', 'Manage and track asset maintenance'),
('Manage Budgets', '/finance/budgets', 'GET', 'View and manage finance budgets'),
('Set Budgets', '/finance/setBudget', 'POST', 'Set new financial budgets'),
('Edit Budget', '/finance/{budgetId}', 'PUT', 'Edit budget details'),
('Delete Budget', '/finance/{budgetId}', 'DELETE', 'Delete a budget'),
('View Financial Reports', '/finance/reports', 'GET', 'View finance reports'),
('Edit Staff', '/hr/{staffId}', 'PUT', 'Edit staff details'),
('Delete Staff', '/hr/{staffId}', 'DELETE', 'Delete a staff member'),
('Edit Payroll', '/hr/EditPayrollPage/{payrollId}', 'PUT', 'Edit payroll details'),
('View Payroll', '/hr/payroll', 'GET', 'View payroll details'),
('Add Payroll', '/hr/addPayroll', 'POST', 'Add a new payroll entry'),
('Add Staff', '/hr/addStaff', 'POST', 'Add a new staff member'),
('Manage Leave Applications', '/hr/leaveApplications', 'GET', 'View and manage leave applications'),
('Add Leave', '/hr/addLeave', 'POST', 'Add a new leave application'),
('View Leave', '/hr/leave', 'GET', 'View leave management system'),
('View Congregation Visitor Records', '/congregation/visitorRecords', 'GET', 'View visitor attendance records'),
('View Programs', '/programs/RegisteredPrograms', 'GET', 'View all registered programs'),
('Manage Attendees', '/programs/attendeeManagement', 'GET', 'Manage program attendees'),
('Add Program', '/programs/addPrograms', 'POST', 'Add a new program'),
('Edit Program', '/programs/{programId}', 'PUT', 'Edit program details'),
('Delete Program', '/programs/{programId}', 'DELETE', 'Delete a program'),
('Edit Attendee', '/programs/editAttendee/{attendeeId}', 'PUT', 'Edit attendee details'),
('Delete Attendee', '/programs/editAttendee/{attendeeId}', 'DELETE', 'Delete an attendee'),
('Add Attendees to Program', '/programs/addAttendees/{programId}', 'POST', 'Add attendees to a program'),
('View Program Details', '/programs/viewProgram', 'GET', 'View details of a program'),
('View Class Details', '/class/classes', 'GET', 'View class details'),
('Manage Class Enrollments', '/class/enrollments', 'POST', 'Manage class enrollments'),
('Class Attendance', '/class/attendance', 'POST', 'Track class attendance'),
('Class Reports', '/class/reports', 'GET', 'View class reports');
